# Generated by Django 3.1.3 on 2022-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20220505_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='avrg',
            field=models.FloatField(null=True),
        ),
    ]
