# Generated by Django 3.1.3 on 2022-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_hotel_avrg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tot',
            field=models.IntegerField(null=True),
        ),
    ]
